services:
  gateway:
    container_name: aincrad-gateway
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - users
      - books
      - loans
    networks:
      - minha-rede
    hostname: gateway-service
  users:
    container_name: aincrad-users
    build: ./users
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/aincrad_users_db
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: 159357
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - minha-rede
    hostname: users-service
  books:
    container_name: aincrad-books
    build: ./books
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/aincrad_books_db
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: 159357
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - minha-rede
    hostname: books-service
  loans:
    container_name: aincrad-loans
    build: ./loans
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/aincrad_loans_db
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: 159357
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - minha-rede
    hostname: loans-service



networks:
  minha-rede:
    ipam:
      driver: bridge
      config:
        - subnet: 172.18.0.0/16
          ip_range: 172.18.0.0/24
          gateway: 172.18.0.1
    external: true